global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: plg-prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: plg-loki
    metrics_path: /metrics
    static_configs:
      - targets: ["loki:3100"]
  - job_name: plg-grafana
    metrics_path: /metrics
    static_configs:
      - targets: ["grafana:3000"]
